account__'{{accountname}}':
    url: '{{url}}'
    login: '{{login}}'

{% block content %}
{% endblock %}

{% block content2 %}
{% endblock %}

{% block content3 %}
{% endblock %}

{% block content4 %}
{% endblock %}
